name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          environment-file: health.yml
          activate-environment: health-record-chatbot

      - name: Initialize Conda
        shell: bash -l {0}
        run: |
          conda init bash
          source ~/.bashrc

      - name: Install dependencies
        run: |
          conda activate health-record-chatbot
          conda info --envs
          conda list

      - name: Build static site
        run: |
          conda activate health-record-chatbot
          python generate_static.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static_site
          exclude_files: |
            **/.*    # Exclude hidden files
            **/new_env/bin/python3.12  # Exclude problematic Python binary reference
